sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
      - libjpeg-turbo-progs
      - jpegoptim
      - optipng
      - pngcrush
# install zopflipng
before_script:
  - git clone https://github.com/google/zopfli
  - cd zopfli
  - make zopflipng
  - export PATH=$PATH:$PWD
  - cd -
# command to install dependencies
install:
  - "pip install ."
  - "pip install coveralls"
script: "python -R setup.py test"
after_success:
  coveralls
